import {auth,db} from './firebase.js'; import {onAuthStateChanged,signOut} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js"; import {collection,doc,getDoc,getDocs,setDoc,deleteDoc,query,orderBy,serverTimestamp} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js"; import {REQUIRE_ACTIVE_SUBSCRIPTION} from './config.js';
let user=null, library=[]; const fields=['youtubeUrl','title','preacher','verses','notes','takeaways']; let saveTimer;
const dailyPassages=[{ref:'Salmos 119:105',text:'Lâmpada para os meus pés é a tua palavra e luz para o meu caminho.'},{ref:'Provérbios 3:5',text:'Confia no Senhor de todo o teu coração e não te estribes no teu próprio entendimento.'},{ref:'Romanos 8:28',text:'Todas as coisas contribuem juntamente para o bem daqueles que amam a Deus.'},{ref:'João 8:32',text:'Conhecereis a verdade, e a verdade vos libertará.'},{ref:'Salmos 23:1',text:'O Senhor é o meu pastor; nada me faltará.'},{ref:'Filipenses 4:13',text:'Posso todas as coisas naquele que me fortalece.'},{ref:'Mateus 11:28',text:'Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei.'},{ref:'Hebreus 11:1',text:'A fé é o firme fundamento das coisas que se esperam e a prova das coisas que se não veem.'}];
function showDailyPassage(){const n=new Date(),k=`${n.getFullYear()}-${n.getMonth()+1}-${n.getDate()}`;let h=0;for(const c of k){h=((h<<5)-h)+c.charCodeAt(0);h|=0}const p=dailyPassages[Math.abs(h)%dailyPassages.length];dailyText.textContent='“'+p.text+'”';dailyRef.textContent=p.ref}
function getYouTubeId(url){if(!url)return null;try{const u=new URL(url.trim());if(u.hostname.includes('youtu.be'))return u.pathname.split('/')[1]?.split('?')[0];if(u.pathname.includes('/shorts/'))return u.pathname.split('/shorts/')[1]?.split('/')[0];if(u.pathname.includes('/embed/'))return u.pathname.split('/embed/')[1]?.split('/')[0];return u.searchParams.get('v')}catch(e){return url.match(/(?:v=|youtu\.be\/|shorts\/|embed\/)([A-Za-z0-9_-]{11})/)?.[1]||null}}
window.loadVideo=function(silent=false){const url=youtubeUrl.value,id=getYouTubeId(url);if(!id){if(!silent)status.textContent='Não consegui identificar esse link.';return}videoWrap.innerHTML=`<iframe src="https://www.youtube.com/embed/${id}?rel=0" title="Pregação no YouTube" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>`;status.textContent='Pregação carregada. Você já pode assistir e fazer suas anotações.';saveDraft()};
async function saveDraft(){if(!user)return;const data={};fields.forEach(id=>data[id]=document.getElementById(id).value);clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{try{await setDoc(doc(db,'users',user.uid,'private','draft'),{...data,updatedAt:serverTimestamp()});saveStatus.textContent='Salvo na nuvem ✓';setTimeout(()=>saveStatus.textContent='Salvamento automático ativado',1600)}catch(e){saveStatus.textContent='Falha ao salvar';console.error(e)}},550)}
async function loadLibrary(){const q=query(collection(db,'users',user.uid,'sermons'),orderBy('savedAt','desc'));const s=await getDocs(q);library=s.docs.map(d=>({id:d.id,...d.data(),savedAt:d.data().savedAt?.toDate?.().toISOString()||d.data().savedAt||''}));renderLibrary()}
window.saveSermon=async function(){const data={};fields.forEach(id=>data[id]=document.getElementById(id).value.trim());if(!data.youtubeUrl&&!data.title&&!data.notes&&!data.verses){alert('Adicione pelo menos o link, título ou alguma anotação antes de salvar.');return}const id=document.body.dataset.editingId||('sermon_'+Date.now());await setDoc(doc(db,'users',user.uid,'sermons',id),{...data,videoId:getYouTubeId(data.youtubeUrl)||'',savedAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});document.body.dataset.editingId=id;await loadLibrary();saveStatus.textContent='Pregação salva na nuvem ✓'};
function esc(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')} function renderLibrary(){if(!library.length){libraryGrid.innerHTML='<div class="empty-library">Sua biblioteca ainda está vazia.<br>Salve sua primeira pregação.</div>';return}libraryGrid.innerHTML=library.map(i=>`<article class="sermon-item" onclick="openSermon('${i.id}')"><button class="delete-sermon" title="Excluir" onclick="event.stopPropagation();deleteSermon('${i.id}')">×</button><h3>${esc(i.title||'Pregação sem título')}</h3><p>${esc(i.preacher||'Pregador não informado')}</p><p>${i.savedAt?'Salva em '+new Date(i.savedAt).toLocaleDateString('pt-BR'):''}</p>${i.verses?`<div class="verse-preview"><strong>Versículos:</strong> ${esc(i.verses.replace(/\n/g,' • ').slice(0,100))}</div>`:''}</article>`).join('')}
window.openSermon=function(id){const i=library.find(x=>x.id===id);if(!i)return;fields.forEach(f=>document.getElementById(f).value=i[f]||'');document.body.dataset.editingId=id;i.youtubeUrl?loadVideo(true):resetVideo();window.scrollTo({top:0,behavior:'smooth'})}; window.deleteSermon=async function(id){if(!confirm('Excluir esta pregação?'))return;await deleteDoc(doc(db,'users',user.uid,'sermons',id));if(document.body.dataset.editingId===id)delete document.body.dataset.editingId;await loadLibrary()};
function resetVideo(){videoWrap.innerHTML='<div class="placeholder"><div><strong>Seu vídeo aparecerá aqui</strong><br><br>Cole o link do YouTube acima para começar.</div></div>'} window.newSermon=async function(){fields.forEach(id=>document.getElementById(id).value='');delete document.body.dataset.editingId;resetVideo();youtubeUrl.focus();await deleteDoc(doc(db,'users',user.uid,'private','draft')).catch(()=>{})}; window.clearNotes=function(){if(!confirm('Deseja realmente apagar todas as anotações desta pregação?'))return;['title','preacher','verses','notes','takeaways'].forEach(id=>document.getElementById(id).value='');saveDraft()}; window.logout=()=>signOut(auth);
fields.forEach(id=>document.getElementById(id).addEventListener('input',saveDraft)); youtubeUrl.addEventListener('keydown',e=>{if(e.key==='Enter')loadVideo()}); showDailyPassage(); onAuthStateChanged(auth,async u=>{if(!u){location.replace('index.html');return}user=u;const us=await getDoc(doc(db,'users',u.uid));const ud=us.data()||{};if(REQUIRE_ACTIVE_SUBSCRIPTION&&ud.subscriptionStatus!=='active'&&ud.plan!=='admin'){location.replace('assinar.html');return}userInfo.textContent=u.displayName||u.email||'';const dr=await getDoc(doc(db,'users',u.uid,'private','draft'));if(dr.exists()){const d=dr.data();fields.forEach(f=>{if(d[f]!=null)document.getElementById(f).value=d[f]});if(d.youtubeUrl)loadVideo(true)}await loadLibrary()});
